services:
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=localdb
    volumes:
      - /postgres-local-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
