services:
  api:
    build: .
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_Environment=Production
      - ConnectionStrings__WebApiDatabase=Server=postgresDb;Port=5432;Database=localdb;User ID=root;Password=password;
    depends_on:
      - postgresDb
  
  postgresDb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=localdb
    volumes:
      - /postgres-prod-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'